[package]
name = "rust_marshal"
version = "0.1.0"
authors = ["Innocent Onyemaenu <innocent.onyemaenu@lixy.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
